server:
  port: 9999

#DataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    port: 587
    username: #你的QQ邮箱
    password: #你的SMTP授权码
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

mybatis-plus:
  typeAliasesPackage: com.tqwc.feastweb.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用


  security:
    user:
      name: admin # 登录用户名
      password: 123456 # 登录密码

security:
  jwt:
    secret: "feast-for-you-jwt-secret-change-me-2026"
    expiration-seconds: 259200
    cookie-name: "FFY_TOKEN"

#=================================================================
# minio
#=================================================================
minio:
  endpoint:
  accessKey:
  secretKey:
  bucketName:



